#ifndef __tonoka_updateCheck__
#define __tonoka_updateCheck__

/**
@file
Subclass of updateCheck, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing updateCheck */
class tonoka_updateCheck : public updateCheck
{
	protected:
		// Handlers for updateCheck events.
		void updateCheckOnInitDialog( wxInitDialogEvent& event );
	public:
		/** Constructor */
		tonoka_updateCheck( wxWindow* parent );
	//// end generated class members

		wxString m_updatetext, m_version, m_message;
};

#endif // __tonoka_updateCheck__
