#ifndef __tonoka_mainFrame__
#define __tonoka_mainFrame__

/**
@file
Subclass of mainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

#include <wx/dirdlg.h>
#include <wx/filedlg.h>
#include <wx/config.h>
#include <wx/busyinfo.h>
#include "tonoka_destination.h"
#include "tonoka_about.h"
#include "tonoka_searchStatus.h"
#include "tonoka_sendStatus.h"
#include "engine.h"
#include <map>

/** Implementing mainFrame */
class tonoka_mainFrame : public mainFrame
{
	protected:
		// Handlers for mainFrame events.
		void OnBrowse( wxCommandEvent& event );
		void OnDestinationEdit( wxCommandEvent& event );
		void m_studiesOnListColClick( wxListEvent& event );
		void OnClear( wxCommandEvent& event );
		void OnLoad( wxCommandEvent& event);
		void OnSave( wxCommandEvent& event);
		void OnUpdate( wxCommandEvent& event );
		void OnSend( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );
		void OnExit( wxCommandEvent& event );
		void OnTextSearch( wxCommandEvent& event);
	public:
		/** Constructor */
		tonoka_mainFrame( wxWindow* parent );
	//// end generated class members

		~tonoka_mainFrame();

		void m_studiesOnListItemChecked(wxListEvent& event);
		void m_studiesOnListItemUnchecked(wxListEvent& event);
		void FillDestinationList();
		void FillStudyList();
		int fillstudiescallback(Study &study);

		engine m_engine;
};

#endif // __tonoka_mainFrame__
