#ifndef __tonoka_about__
#define __tonoka_about__

/**
@file
Subclass of about, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing about */
class tonoka_about : public about
{
	public:
		/** Constructor */
		tonoka_about( wxWindow* parent );
	//// end generated class members
	
};

#endif // __tonoka_about__
