# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


TEMPLATE = subdirs
SUBDIRS += openjp2/openjp2.pro \
           openjp2/opj_compress.pro \
           openjp2/opj_decompress.pro \
           openjp2/opj_dump.pro
