#ifndef __finaco_moveStatus__
#define __finaco_moveStatus__

/**
@file
Subclass of moveStatus, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#include "dicommover.h"
#include <wx/timer.h>

/** Implementing moveStatus */
class finaco_moveStatus : public moveStatus
{
    protected:
        // Handlers for moveStatus events.
        void OnStop( wxCommandEvent& event );
    public:
        /** Constructor */
        finaco_moveStatus( wxWindow* parent );
    //// end generated class members    

        ~finaco_moveStatus();
        wxTimer timer;
        void OnTimer(wxTimerEvent& event);
        DICOMMover *m_mover;

};

#endif // __finaco_moveStatus__
