#ifndef __finaco_destination__
#define __finaco_destination__

/**
@file
Subclass of destination, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

#include <wx/msgdlg.h>
#include <vector>
#include "destinationentry.h"
#include <wx/valtext.h>
#include <wx/valnum.h>
#include <boost/lexical_cast.hpp>
#include "dicomquery.h"

/** Implementing destination */
class finaco_destination : public destination
{
	protected:
		// Handlers for destination events.
		void OnInitDialog( wxInitDialogEvent& event );
		void OnDeselected( wxListEvent& event );
		void OnSelect( wxListEvent& event );
		void OnAdd( wxCommandEvent& event );
		void OnDelete( wxCommandEvent& event );
		void OnEcho( wxCommandEvent& event );
		void OnNameText( wxCommandEvent& event );
		void OnDestinationHostText( wxCommandEvent& event );
		void OnDestinationPortText( wxCommandEvent& event );
		void OnDestinationAETitleText( wxCommandEvent& event );
		void OnOurAETitleText( wxCommandEvent& event );
		void OnOK( wxCommandEvent& event );
	public:
		/** Constructor */
		finaco_destination( wxWindow* parent );
	//// end generated class members

		std::vector<DestinationEntry> m_destinations;
		void SetCtrlState();
		void UpdateItem(int sel = -1);
		int GetSelectedDestinationItem();

		wxString invalidInput;


};

#endif // __finaco_destination__
