#ifndef __finaco_about__
#define __finaco_about__

/**
@file
Subclass of about, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing about */
class finaco_about : public about
{
	public:
		/** Constructor */
		finaco_about( wxWindow* parent );
	//// end generated class members


};

#endif // __finaco_about__
