#ifndef __finaco_searchStatus__
#define __finaco_searchStatus__

/**
@file
Subclass of searchStatus, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#include "dicomquery.h"
#include <wx/timer.h>

/** Implementing searchStatus */
class finaco_searchStatus : public searchStatus
{
    protected:
        // Handlers for searchStatus events.
        void OnStop( wxCommandEvent& event );
    public:
        /** Constructor */
        finaco_searchStatus( wxWindow* parent );
    //// end generated class members

        ~finaco_searchStatus();
        wxTimer timer;
        void OnTimer(wxTimerEvent& event);
        DICOMQueryScanner *m_scanner;


};

#endif // __finaco_searchStatus__
