# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT       += core gui widgets  concurrent
force_debug_info
#greaterThan(QT_MAJOR_VERSION, 4): QT += widgets concurrent
#CONFIG += c++11

TEMPLATE = app
TARGET   = CPR
DESTDIR  = ./bin
#CONFIG += debug console
QMAKE_MACOSX_DEPLOYMENT_TARGET = 13.0
QMAKE_MAC_XARCHS = x86_64

HEADERS +=  ./QtVTKRenderWindows.h \
    vtkFrenetSerretFrame.h \
    vtkSplineDrivenImageSlicer.h

SOURCES +=  ./QtVTKRenderWindows.cxx \
            ./QtVTKRenderWindowsApp.cxx \
            vtkFrenetSerretFrame.cxx \
            vtkSplineDrivenImageSlicer.cxx

FORMS   += ./QtVTKRenderWindows.ui

SDK_INSTALL_PREFIX = /Users/bitter/Documents/SDK

# VTK Libraries

VTKLIBDIR = $$(VTKLIBDIR)
isEmpty(VTKLIBDIR){
    unix:VTKLIBDIR = $$SDK_INSTALL_PREFIX/VTK/VTK-9.4.0S/lib
    win32:VTKLIBDIR = $$SDK_INSTALL_PREFIX/VTK/8.2.0/libshare
}
VTKINCLUDEDIR = $$(VTKINCLUDEDIR)
isEmpty(VTKINCLUDEDIR){
    unix:VTKINCLUDEDIR = $$SDK_INSTALL_PREFIX/VTK/VTK-9.4.0
    win32:VTKINCLUDEDIR = $$SDK_INSTALL_PREFIX/VTK/8.2.0/include
}

#------------------------------------------------------------VTK8.2.0-------------------------------------
INCLUDEPATH +=  $${VTKINCLUDEDIR} \
                $${VTKINCLUDEDIR}/more/ \
                $${VTKINCLUDEDIR}/Common/Core/ \
                $${VTKINCLUDEDIR}/Common/DataModel/ \
                $${VTKINCLUDEDIR}/Common/Math/ \
                $${VTKINCLUDEDIR}/Common/ComputationalGeometry/ \
                $${VTKINCLUDEDIR}/Common/ExecutionModel/ \
                $${VTKINCLUDEDIR}/Common/Misc/ \
                $${VTKINCLUDEDIR}/Common/System/ \
                $${VTKINCLUDEDIR}/Common/Transforms/ \
                $${VTKINCLUDEDIR}/Common/Color/ \
                $${VTKINCLUDEDIR}/Imaging/Core/ \
                $${VTKINCLUDEDIR}/Imaging/Color/ \
                $${VTKINCLUDEDIR}/Imaging/Fourier/ \
                $${VTKINCLUDEDIR}/Imaging/General/ \
                $${VTKINCLUDEDIR}/Imaging/Hybrid/ \
                $${VTKINCLUDEDIR}/Imaging/Math/ \
                $${VTKINCLUDEDIR}/Imaging/Morphological/ \
                $${VTKINCLUDEDIR}/Imaging/OpenGL2/ \
                $${VTKINCLUDEDIR}/Imaging/Sources/ \
                $${VTKINCLUDEDIR}/Imaging/Statistics/ \
                $${VTKINCLUDEDIR}/Imaging/Stencil/ \
                $${VTKINCLUDEDIR}/IO/ADIOS/ \
                $${VTKINCLUDEDIR}/IO/Core/ \
                $${VTKINCLUDEDIR}/IO/EnSight/ \
                $${VTKINCLUDEDIR}/IO/Exodus/ \
                $${VTKINCLUDEDIR}/IO/Export/ \
                $${VTKINCLUDEDIR}/IO/ExportOpenGL/ \
                $${VTKINCLUDEDIR}/IO/ExportOpenGL2/ \
                $${VTKINCLUDEDIR}/IO/FFMPEG/ \
                $${VTKINCLUDEDIR}/IO/GDAL/ \
                $${VTKINCLUDEDIR}/IO/GeoJSON/ \
                $${VTKINCLUDEDIR}/IO/Geometry/ \
                $${VTKINCLUDEDIR}/IO/Image/ \
                $${VTKINCLUDEDIR}/IO/Import/ \
                $${VTKINCLUDEDIR}/IO/Infovis/ \
                $${VTKINCLUDEDIR}/IO/LAS/ \
                $${VTKINCLUDEDIR}/IO/Legacy/ \
                $${VTKINCLUDEDIR}/IO/LSDyna/ \
                $${VTKINCLUDEDIR}/IO/MINC/ \
                $${VTKINCLUDEDIR}/IO/Movie/ \
                $${VTKINCLUDEDIR}/IO/MPIImage/ \
                $${VTKINCLUDEDIR}/IO/MPIParallel/ \
                $${VTKINCLUDEDIR}/IO/MySQL/ \
                $${VTKINCLUDEDIR}/IO/NetCDF/ \
                $${VTKINCLUDEDIR}/IO/ODBC/ \
                $${VTKINCLUDEDIR}/IO/Parallel/ \
                $${VTKINCLUDEDIR}/IO/ParallelExodus/ \
                $${VTKINCLUDEDIR}/IO/ParallelLSDyna/ \
                $${VTKINCLUDEDIR}/IO/ParallelNetCDF/ \
                $${VTKINCLUDEDIR}/IO/ParallelXdmf3/ \
                $${VTKINCLUDEDIR}/IO/ParallelXML/ \
                $${VTKINCLUDEDIR}/IO/PDAL/ \
                $${VTKINCLUDEDIR}/IO/PLY/ \
                $${VTKINCLUDEDIR}/IO/PostgreSQL/ \
                $${VTKINCLUDEDIR}/IO/SegY/ \
                $${VTKINCLUDEDIR}/IO/TecplotTable/ \
                $${VTKINCLUDEDIR}/IO/Video/ \
                $${VTKINCLUDEDIR}/IO/VPIC/ \
                $${VTKINCLUDEDIR}/IO/Xdmf2/ \
                $${VTKINCLUDEDIR}/IO/Xdmf3/ \
                $${VTKINCLUDEDIR}/IO/XML/ \
                $${VTKINCLUDEDIR}/IO/XMLParser/ \
                $${VTKINCLUDEDIR}/GUISupport/MFC/ \
                $${VTKINCLUDEDIR}/GUISupport/Qt/ \
                $${VTKINCLUDEDIR}/GUISupport/QtOpenGL/ \
                $${VTKINCLUDEDIR}/GUISupport/QtSQL/ \
                $${VTKINCLUDEDIR}/GUISupport/QtWebkit/ \
                $${VTKINCLUDEDIR}/Rendering/Annotation/ \
                $${VTKINCLUDEDIR}/Rendering/Context2D/ \
                $${VTKINCLUDEDIR}/Rendering/ContextOpenGL/ \
                $${VTKINCLUDEDIR}/Rendering/ContextOpenGL2/ \
                $${VTKINCLUDEDIR}/Rendering/Core/ \
                $${VTKINCLUDEDIR}/Rendering/External/ \
                $${VTKINCLUDEDIR}/Rendering/FreeType/ \
                $${VTKINCLUDEDIR}/Rendering/FreeTypeFontConfig/ \
                $${VTKINCLUDEDIR}/Rendering/GL2PS/ \
                $${VTKINCLUDEDIR}/Rendering/GL2PSOpenGL2/ \
                $${VTKINCLUDEDIR}/Rendering/Label/ \
                $${VTKINCLUDEDIR}/Rendering/Image/ \
                $${VTKINCLUDEDIR}/Rendering/Core/ \
                $${VTKINCLUDEDIR}/Rendering/LIC/ \
                $${VTKINCLUDEDIR}/Rendering/LICOpenGL2/ \
                $${VTKINCLUDEDIR}/Rendering/LOD/ \
                $${VTKINCLUDEDIR}/Rendering/Matplotlib/ \
                $${VTKINCLUDEDIR}/Rendering/Oculus/ \
                $${VTKINCLUDEDIR}/Rendering/OpenGL/ \
                $${VTKINCLUDEDIR}/Rendering/OpenGL2/ \
                $${VTKINCLUDEDIR}/Rendering/OpenVR/ \
                $${VTKINCLUDEDIR}/Rendering/External/ \
                $${VTKINCLUDEDIR}/Rendering/OptiX/ \
                $${VTKINCLUDEDIR}/Rendering/OSPRay/ \
                $${VTKINCLUDEDIR}/Rendering/GL2PS/ \
                $${VTKINCLUDEDIR}/Rendering/Parallel/ \
                $${VTKINCLUDEDIR}/Rendering/ParallelLIC/ \
                $${VTKINCLUDEDIR}/Rendering/Qt/ \
                $${VTKINCLUDEDIR}/Rendering/SceneGraph/ \
                $${VTKINCLUDEDIR}/Rendering/Tk/ \
                $${VTKINCLUDEDIR}/Rendering/Volume/ \
                $${VTKINCLUDEDIR}/Rendering/VolumeAMR/ \
                $${VTKINCLUDEDIR}/Rendering/VolumeOpenGL/ \
                $${VTKINCLUDEDIR}/Rendering/VolumeOpenGL2/ \
                $${VTKINCLUDEDIR}/Filters/Core/ \
                $${VTKINCLUDEDIR}/Filters/Extraction/ \
                $${VTKINCLUDEDIR}/Filters/FlowPaths/ \
                $${VTKINCLUDEDIR}/Filters/General/ \
                $${VTKINCLUDEDIR}/Filters/Generic/ \
                $${VTKINCLUDEDIR}/Filters/Geometry/ \
                $${VTKINCLUDEDIR}/Filters/Hybrid/ \
                $${VTKINCLUDEDIR}/Filters/HyperTree/ \
                $${VTKINCLUDEDIR}/Filters/Imaging/ \
                $${VTKINCLUDEDIR}/Filters/Modeling/ \
                $${VTKINCLUDEDIR}/Filters/OpenTurns/ \
                $${VTKINCLUDEDIR}/Filters/Parallel/ \
                $${VTKINCLUDEDIR}/Filters/ParallelDIY2/ \
                $${VTKINCLUDEDIR}/Filters/ParallelFlowPaths/ \
                $${VTKINCLUDEDIR}/Filters/ParallelGeometry/ \
                $${VTKINCLUDEDIR}/Filters/ParallelImaging/ \
                $${VTKINCLUDEDIR}/Filters/ParallelMPI/ \
                $${VTKINCLUDEDIR}/Filters/ParallelStatistics/ \
                $${VTKINCLUDEDIR}/Filters/ParallelVerdict/ \
                $${VTKINCLUDEDIR}/Filters/Points/ \
                $${VTKINCLUDEDIR}/Filters/Programmable/ \
                $${VTKINCLUDEDIR}/Filters/Python/ \
                $${VTKINCLUDEDIR}/Filters/ReebGraph/ \
                $${VTKINCLUDEDIR}/Filters/Selection/ \
                $${VTKINCLUDEDIR}/Filters/SMP/ \
                $${VTKINCLUDEDIR}/Filters/Sources/ \
                $${VTKINCLUDEDIR}/Filters/Statistics/ \
                $${VTKINCLUDEDIR}/Filters/Qt/ \
                $${VTKINCLUDEDIR}/Filters/SceneGraph/ \
                $${VTKINCLUDEDIR}/Filters/Texture/ \
                $${VTKINCLUDEDIR}/Utilities/KWIML/ \
                $${VTKINCLUDEDIR}/Utilities/KWIML/vtkkwiml/ \
                $${VTKINCLUDEDIR}/Interaction/Widgets/ \
                $${VTKINCLUDEDIR}/Interaction/Style/ \
                $${VTKINCLUDEDIR}/Interaction/Image/ \
                $${VTKINCLUDEDIR}/Filters/Verdict/ \
                $${VTKINCLUDEDIR}/ThirdParty/nlohmannjson

#vtkInteractionWidgetsModule.h
#/Users/bitter/Documents/SDK/VTK-910b/Interaction

VTKINCLUDE_BUILD_DIR = $$(VTKINCLUDE_BUILD_DIR)
isEmpty(VTKINCLUDE_BUILD_DIR){
    unix:VTKINCLUDE_BUILD_DIR = $$SDK_INSTALL_PREFIX/VTK/VTK-9.4.0S
    win32:VTKINCLUDEDIR = $$SDK_INSTALL_PREFIX/VTK/8.2.0/include
}
#VTKINCLUDE_BUILD_DIR = /Users/bitter/Documents/SDK/VTK-910b
INCLUDEPATH +=  $${VTKINCLUDE_BUILD_DIR} \
                $${VTKINCLUDE_BUILD_DIR}/more/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/DataModel/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/Math/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/ComputationalGeometry/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/ExecutionModel/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/Misc/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/System/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/Transforms/ \
                $${VTKINCLUDE_BUILD_DIR}/Common/Color/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Color/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Fourier/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/General/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Hybrid/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Math/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Morphological/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/OpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Sources/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Statistics/ \
                $${VTKINCLUDE_BUILD_DIR}/Imaging/Stencil/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ADIOS/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/EnSight/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Exodus/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Export/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ExportOpenGL/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ExportOpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/FFMPEG/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/GDAL/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/GeoJSON/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Geometry/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Image/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Import/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Infovis/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/LAS/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Legacy/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/LSDyna/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/MINC/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Movie/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/MPIImage/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/MPIParallel/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/MySQL/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/NetCDF/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ODBC/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Parallel/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ParallelExodus/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ParallelLSDyna/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ParallelNetCDF/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ParallelXdmf3/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/ParallelXML/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/PDAL/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/PLY/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/PostgreSQL/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/SegY/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/TecplotTable/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Video/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/VPIC/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Xdmf2/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/Xdmf3/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/XML/ \
                $${VTKINCLUDE_BUILD_DIR}/IO/XMLParser/ \
                $${VTKINCLUDE_BUILD_DIR}/GUISupport/MFC/ \
                $${VTKINCLUDE_BUILD_DIR}/GUISupport/Qt/ \
                $${VTKINCLUDE_BUILD_DIR}/GUISupport/QtOpenGL/ \
                $${VTKINCLUDE_BUILD_DIR}/GUISupport/QtSQL/ \
                $${VTKINCLUDE_BUILD_DIR}/GUISupport/QtWebkit/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Annotation/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Context2D/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/ContextOpenGL/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/ContextOpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/External/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/FreeType/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/FreeTypeFontConfig/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/GL2PS/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/GL2PSOpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Label/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Image/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/LIC/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/LICOpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/LOD/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Matplotlib/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Oculus/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/OpenGL/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/OpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/OpenVR/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/External/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/OptiX/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/OSPRay/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/GL2PS/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Parallel/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/ParallelLIC/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Qt/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/SceneGraph/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Tk/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/Volume/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/VolumeAMR/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/VolumeOpenGL/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/VolumeOpenGL2/ \
                $${VTKINCLUDE_BUILD_DIR}/Rendering/UI/ \
               $${VTKINCLUDE_BUILD_DIR}/Rendering/HyperTreeGrid/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Core/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Extraction/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/FlowPaths/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/General/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Generic/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Geometry/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Hybrid/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/HyperTree/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Imaging/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Modeling/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/OpenTurns/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Parallel/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelDIY2/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelFlowPaths/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelGeometry/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelImaging/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelMPI/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelStatistics/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ParallelVerdict/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Points/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Programmable/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Python/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/ReebGraph/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Selection/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/SMP/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Sources/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Statistics/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Qt/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/SceneGraph/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Texture/ \
                $${VTKINCLUDE_BUILD_DIR}/Utilities/KWIML/ \
                $${VTKINCLUDE_BUILD_DIR}/Utilities/KWSys/ \
                $${VTKINCLUDE_BUILD_DIR}/Utilities/KWIML/vtkkwiml/ \
                $${VTKINCLUDE_BUILD_DIR}/Interaction/Widgets/ \
                $${VTKINCLUDE_BUILD_DIR}/Interaction/Style/ \
                $${VTKINCLUDE_BUILD_DIR}/Interaction/Image/ \
                $${VTKINCLUDE_BUILD_DIR}/Filters/Verdict/ \
                $${VTKINCLUDE_BUILD_DIR}/ThirdParty/nlohmannjson


INCLUDEPATH +=  /Users/bitter/Documents/SDK/Threadweaver/threadweaver-5.46.0  \
                                  /Users/bitter/Documents/SDK/Threadweaver/threadweaver-5.46.0/src \
                                  /Users/bitter/Documents/SDK/Threadweaver/threadweaver-5.46.0S/src



VTKLIBDIR = $$(VTKLIBDIR)
isEmpty(VTKLIBDIR){
        unix:VTKLIBDIR = $$SDK_INSTALL_PREFIX/VTK/VTK-9.4.0S/lib/lib
}
VTKLIBSUFFIX = -9.4.a
VTKLIBS = \
                    vtkCommonCore                                  \
                    vtkCommonDataModel                        \
                    vtkCommonExecutionModel       \
                    vtkCommonTransforms           \
                    vtkCommonComputationalGeometry   \
                    vtkFiltersCore                          \
                    vtkFiltersModeling          \
                    vtkRenderingCore              \
                    vtkRenderingFreeType          \
                    vtkRenderingOpenGL2           \
                    vtkRenderingUI                         \
                    vtkInteractionStyle           \
                    vtkInteractionWidgets            \
                    vtkCommonMath                 \
                    vtkCommonMisc                 \
                    vtkCommonColor   \
                    vtkCommonSystem               \
                    vtkFiltersGeneral             \
                    vtkFiltersSources             \
                    vtkFiltersExtraction           \
                    vtkFiltersStatistics              \
                    vtkVerdict             \
                    vtkFiltersGeometry              \
                    vtkFiltersTexture                 \
                    vtkFiltersCellGrid                    \
                    vtkGUISupportQt               \
                    vtkDICOMParser                  \
                    vtkImagingCore                \
                    vtkImagingGeneral             \
                    vtkglad                           \
                    vtkImagingHybrid              \
                    vtkParallelDIY                  \
                    vtkImagingMath                \
                    vtkInteractionImage        \
                    vtkImagingGeneral        \
                    vtkIOImage                    \
                    vtkIOCore                    \
                    vtkIOXML                                \
                    vtkIOXMLParser                     \
                    vtkRenderingAnnotation        \
                    vtkRenderingImage             \
                    vtkRenderingVolume            \
                    vtkRenderingVolumeOpenGL2     \
                    vtkRenderingContext2D  \
                    vtkRenderingHyperTreeGrid        \
                    vtkpugixml                \
                    vtksys          \
                    vtktiff                       \
                    vtkjpeg                       \
                    vtkpng                        \
                    vtkmetaio                     \
                    vtkIOLegacy                  \
                    vtkIOCellGrid                  \
                    #vtkglew                       \
                    vtkImagingColor             \
                    vtkfreetype                   \
                    vtkFiltersGeometry            \
                    vtkFiltersReduction            \
                    vtkFiltersHyperTree               \
                    vtkFiltersVerdict                      \
                    vtkCommonColor                \
                    vtkzlib                       \
                    vtktoken                   \
                    vtkChartsCore   \
                    vtkIOCore  \
                    vtkpugixml  \
                    vtkdoubleconversion  \
                    vtkFiltersGeneral  \
                    vtkFiltersModeling  \
                    vtkFiltersHybrid  \
                    vtkImagingSources  \
                    vtkParallelCore  \
                    vtkParallelDIY  \
                    vtkImagingGeneral  \
                    vtkFiltersExtraction           \
                    vtkpugixml   \
                    vtkdoubleconversion  \
                    vtkInfovisCore             \
                    vtkloguru  \           # 解决所有 vtkloguru::xxx
                    vtkfmt  \              # 解决 vtkfmt::vformat
                    vtkkissfft  \          # 解决 _vtkkissfft_fft 等
                    vtklz4  \              # 解决 _vtklz4_LZ4_xxx
                    vtklzma  \             # 解决 _vtklzma_xxx
                    vtkexpat  \            # vtkXMLParser 依赖 expat（最关键！）
                    vtkzlib               # zlib 压缩



#LIBS += -L$${VTKLIBDIR}
#LIBS += $$SDK_INSTALL_PREFIX/VTK-910b/lib/libvtkCommonCore-9.1.a
#for(lib, LIBS) {
#    LIBS += $${lib}
#    #LIBS += $$join(-l,$${lib}$${VTKLIBSUFFIX})
#}

LIBS += -L$${VTKLIBDIR}

for(lib, VTKLIBS) {
    LIBS += -Wl,-force_load,$${VTKLIBDIR}$${lib}$${VTKLIBSUFFIX}
}


#LIBS += -L/Users/bitter/Documents/SDK/Threadweaver/threadweaverQT-5.46.0
#LIBS += -lKF5ThreadWeaver


LIBS += -framework Cocoa -framework OpenGL  -framework  IOKit   -framework CoreFoundation
LIBS += -lz -lexpat    -llzma

LIBS += /Users/bitter/Documents/SDK/Threadweaver/threadweaver-5.46.0S/src/libKF5ThreadWeaver.a

#unix: {
#    QMAKE_CXXFLAGS += -stdlib=libc++
#    QMAKE_LFLAGS += -stdlib=libc++
#    LIBS += -framework Cocoa
#    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.11
#}

#contains(QT_ARCH,x86_64){
#message("64-bit")
#}else{
#message("32-bit")
#}


qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

